# Generated by Django 4.1.3 on 2022-11-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("resumetask", models.TextField()),
                (
                    "done",
                    models.CharField(
                        choices=[("doing", "Doing"), ("done", "Done")], max_length=5
                    ),
                ),
            ],
        ),
    ]
