# Generated by Django 4.1.3 on 2022-12-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="resumetask",
            field=models.TextField(max_length=400),
        ),
    ]
