# Generated by Django 4.1.3 on 2022-12-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_resumetask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="resumetask",
            field=models.TextField(max_length=400, verbose_name="resumetask"),
        ),
    ]
